# Generated by Django 5.0.7 on 2024-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='minute',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
