# Generated by Django 5.0.7 on 2024-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_schedule_hour_remove_schedule_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bell_sound',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notification_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
