# Generated by Django 5.0.7 on 2024-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_schedule_bell_sound_schedule_notification_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='notification_day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='notification_days',
            field=models.ManyToManyField(blank=True, to='data.day'),
        ),
    ]
