# Generated by Django 5.0.7 on 2024-07-15 13:24

from django.db import migrations

def insert_initial_data(apps, schema_editor):
    # Get models
    Day = apps.get_model('data', 'Day')
    Bell = apps.get_model('data', 'Bell')

    # Insert initial data for Day model
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    for day in days:
        Day.objects.get_or_create(name=day)

    # Insert initial data for Bell model
    Bell.objects.create(name='เสียงเตือนที่ 1', first='audio/bell/sound1/First.wav', last='audio/bell/sound1/Last.wav', status=0)
    Bell.objects.create(name='เสียงเตือนที่ 2', first='audio/bell/sound2/First.wav', last='audio/bell/sound2/Last.wav', status=0)
    Bell.objects.create(name='เสียงเตือนที่ 3', first='audio/bell/sound3/First.wav', last='audio/bell/sound3/Last.wav', status=1)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_day_remove_schedule_notification_day_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data),
    ]
