# Generated by Django 5.0.7 on 2024-07-15 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20240715_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='bell_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.bell'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tell_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tell_time',
            field=models.ManyToManyField(blank=True, to='data.audio'),
        ),
    ]
