# Generated by Django 5.0.7 on 2024-07-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_audio_alter_schedule_bell_sound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tell_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tell_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.audio'),
        ),
    ]
