# Generated by Django 5.0.7 on 2024-07-15 23:20

from django.db import migrations
import os

def add_audio_from_directory(apps, schema_editor):
    Audio = apps.get_model('data', 'Audio')

    # Directories where audio files are located
    directories = ['audio/thai', 'audio/eng']

    for directory in directories:
        for filename in os.listdir(directory):
            if filename.endswith(".wav") or filename.endswith(".mp3"):  # Adjust file types as needed
                file_path = os.path.join(directory, filename)
                audio_name = os.path.splitext(filename)[0]  # Use filename without extension as name
                audio_path = file_path  # Use full file path as path (adjust as needed)

                # Create Audio object and save to database
                Audio.objects.create(name=audio_name, path=audio_path)

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_schedule_tell_time_schedule_tell_time'),
    ]

    operations = [
        migrations.RunPython(add_audio_from_directory),
    ]
