# Generated by Django 5.0.7 on 2024-07-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_add_audio_from_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.audio'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tell_time',
            field=models.BooleanField(default=True),
        ),
    ]
