# Generated by Django 5.0.7 on 2024-07-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_schedule_status_alter_schedule_sound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sound_eng',
        ),
    ]
