# Generated by Django 5.0.7 on 2024-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_schedule_sound_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='name_eng',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
