# Generated by Django 5.0.7 on 2024-07-16 11:33

from django.db import migrations

def add_day_names_eng(apps, schema_editor):
    Day = apps.get_model('data', 'Day')
    days_thai = ['จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์', 'อาทิตย์']
    days_eng = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

    for day, day_eng in zip(days_thai, days_eng):
        day_obj = Day.objects.get_or_create(name=day)[0]
        day_obj.name_eng = day_eng
        day_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_day_name_eng'),
    ]

    operations = [
        migrations.RunPython(add_day_names_eng),
    ]
