# Generated by Django 5.0.7 on 2024-11-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20240716_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
