# Generated by Django 5.1.7 on 2025-05-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_utility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='enable_bell_sound',
            field=models.BooleanField(default=True),
        ),
    ]
